home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home, name='home'),
    path('programme', views.Programme, name='programme'),
    path('offres', views.Offres, name='offres'),
    path('about', views.About, name='about'),
    path('jophi_soja', views.Soja, name='soja'),
    path('search/', views.search, name='search'),

    path('domaine/agriculture', views.DomaineAgri, name='agri'),
    path('domaine/economie', views.DomaineEcon, name='econ'),
    path('domaine/environement', views.DomaineEnv, name='env'),
    path('domaine/infrastructure', views.DomaineInfra, name='infra'),
    path('domaine/reboisement', views.DomaineReb, name='reb'),
    path('domaine/urgence', views.DomaineUrgence, name='urgence'),

    path('mission/formulaire-devis', views.DevisForm, name='devis-form'),
    
    path('ecoplus', views.Ecoplus, name='ecoplus'),
    path('dashboard/', views.Dashboard, name='dash'),

    path('addMission/', views.addMission.as_view(), name='addMission'),
    path('showMission/', views.showMission, name='showMission'),
    path('updateMission/<pk>', views.updateMission.as_view(), name='updateMission'),

    path('addDomaine/', views.addDomaine.as_view(), name='addDomaine'),
    path('showDomaine/', views.showDomaine, name='showDomaine'),
    path('updateDomain/<pk>', views.updateDomaine.as_view(), name='updateDomain'),
    path('deleteDomain/<pk>', views.deleteDomaine, name='deleteDomain'),

    path('addContact/', views.addContact.as_view(), name='addContact'),
    path('showContact/', views.showContact, name='showContact'),

    path('addOffre/', views.addOffre.as_view(), name='addOffre'),
    path('showOffre/', views.showOffre, name='showOffre'),

    path('addCommande/', views.addCommandeSoja.as_view(), name='addCommande'),
    path('showCommande/', views.showCommandeSoja, name='showCommande'),
]

tbf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
 
# Custom 404 error view
handler404 = 'home.views.error_404' 
# Custom 500 error view
handler500 = 'home.views.error_500' 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

class Mission(models.Model):
    image = models.ImageField(upload_to="image/")
    title = models.CharField(max_length=100)
    desc = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.title}'

class Domaine(models.Model):
    parent = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="domaine/")
    detail = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.title} - {self.parent}'

class Offre(models.Model):
    title = models.CharField(max_length=50)
    detail = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="domaine/", blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.title}'

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} ({self.email})'

class CommandeSoja(models.Model):
    name = models.CharField(max_length=50)
    midname = models.CharField(max_length=50)
    firstname = models.CharField(max_length=50)
    email = models.EmailField()
    numero = models.CharField(max_length=50)
    adress = models.CharField(max_length=50)
    quantite = models.CharField(max_length=5)
    details = models.TextField(null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} {self.midname} {self.firstname} {self.numero}'

home/forms.py
from django import forms
from .models import Mission, Domaine

class MissionForm(forms.ModelForm):
    class Meta:
        model = Mission
        fields = ["title", "description", "image"]

class DomaineForm(forms.ModelForm):
    class Meta:
        model = Domaine
        fields = ["title", "detail", "desc", "image"]

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from .models import Mission, Domaine, Offre, Contact, CommandeSoja


def Home(request):
    template_name = 'home/index.html'
    missions = Mission.objects.all()
    context = {
        'missions': missions,
    }
    return render(request, template_name, context)

def Programme(request):
    template_name = 'home/programme.html'
    return render(request, template_name)

def About(request):
    template_name = 'home/about.html'
    return render(request, template_name)

def Soja(request):
    template_name = 'home/soja.html'
    return render(request, template_name)

def Offres(request):
    template_name = 'home/offres.html'
    offres = Offre.objects.all()
    context = {
        'offres': offres,
    }
    return render(request, template_name, context)


def error_404(request, exception):
    return render(request, 'error_404.html', status=404)
 
def error_500(request):
    return render(request, 'error_505.html', status=500)
 
def search(request):
    return render(request, 'home/search.html')



def DomaineAgri(request):
    template_name = 'domaine/agriculture.html'
    domaines = Domaine.objects.all()
    context = {
        'domaines': domaines,
    }
    return render(request, template_name, context)

def DomaineEcon(request):
    template_name = 'domaine/economie.html'
    domaines = Domaine.objects.all()
    context = {
        'domaines': domaines,
    }
    return render(request, template_name, context)

def DomaineEnv(request):
    template_name = 'domaine/environement.html'
    domaines = Domaine.objects.all()
    context = {
        'domaines': domaines,
    }
    return render(request, template_name, context)

def DomaineInfra(request):
    template_name = 'domaine/infrastructure.html'
    domaines = Domaine.objects.all()
    context = {
        'domaines': domaines,
    }
    return render(request, template_name, context)

def DomaineReb(request):
    template_name = 'domaine/reboisement.html'
    domaines = Domaine.objects.all()
    context = {
        'domaines': domaines,
    }
    return render(request, template_name, context)

def DomaineUrgence(request):
    template_name = 'domaine/urgence.html'
    domaines = Domaine.objects.all()
    context = {
        'domaines': domaines,
    }
    return render(request, template_name, context)



def DevisForm(request):
    template_name = 'mission/formulaire-devis.html'
    return render(request, template_name)



def Ecoplus(request):
    template_name = 'ecoplus/index.html'
    return render(request, template_name)

def Dashboard(request):
    template_name = 'admin/admin.html'
    return render(request, template_name)



class addMission(CreateView):
    model = Mission
    fields = ['title', 'image', 'desc']
    success_url = '/showMission/'
    template_name = 'dash/addMission.html'

def showMission(request):
    template_name = 'dash/missions.html'
    missions = Mission.objects.all()
    context = {
        'missions': missions,
    }
    return render(request, template_name, context)

class updateMission(UpdateView):
    model = Mission
    fields = ['title', 'image', 'desc']
    success_url = "/showMission/"
    template_name = 'dash/updateMission.html'



class addDomaine(CreateView):
    model = Domaine
    fields = ['parent', 'title', 'detail', 'image']
    success_url = '/showDomaine/'
    template_name = 'dash/addDomaine.html'

def showDomaine(request):
    template_name = 'dash/domaines.html'
    domaines = Domaine.objects.all()
    context = {
        'domaines': domaines,
    }
    return render(request, template_name, context)

class updateDomaine(UpdateView):
    model = Domaine
    fields = ['parent', 'title', 'detail', 'image']
    success_url = "/showDomaine/"
    template_name = 'dash/updateDomaine.html'

def deleteDomaine(request, pk):
    obj = Domaine.objects.get(id = pk)
    template_name = 'dash/domains.html'
    if request.method == "POST":
        obj.delete()
        return redirect("home:showDomaine")
    return render(request, template_name)



class addOffre(CreateView):
    model = Offre
    fields = ['title', 'detail', 'image']
    success_url = '/showOffre/'
    template_name = 'dash/addOffre.html'

def showOffre(request):
    template_name = 'dash/Offres.html'
    offres = Offre.objects.all()
    context = {
        'offres': offres,
    }
    return render(request, template_name, context)



class addContact(CreateView):
    model = Contact
    fields = ['name', 'email', 'message']
    success_url = '/'
    template_name = 'home/index.html'

def showContact(request):
    template_name = 'dash/contacts.html'
    contacts = Contact.objects.all()
    context = {
        'contacts': contacts,
    }
    return render(request, template_name, context)


class addCommandeSoja(CreateView):
    model = CommandeSoja
    fields = ['name', 'midname', 'firstname', 'email', 'numero', 'adress', 'quantite', 'details']
    success_url = '/programme/soja'
    template_name = 'home/soja.html'

def addCommande(request):
    template_name = 'home/soja.html'
    if request.method == 'POST':
        name = request.POST.get('name')
        midname = request.POST.get('midname')
        firstname = request.POST.get('firstname')
        numero = request.POST.get('numero')
        email = request.POST.get('email')
        adress = request.POST.get('adress')
        quantite = request.POST.get('quantite')
        details = request.POST.get('details')
        data = CommandeSoja(name, midname, firstname, numero, email, adress, quantite, details)
        data.save()
        messages.success(request, 'Votre commande a été envoyé avec success')
        return redirect('home:soja')
    return render(request, template_name)

def showCommandeSoja(request):
    template_name = 'dash/commandes.html'
    commandes = CommandeSoja.objects.all()
    context = {
        'commandes': commandes,
    }
    return render(request, template_name, context)



class DashboardView(ListView):
    template_name = 'admin/admin.html'

templates/home/about.html
{% extends './base.html' %}
{% load static %}
{% block content %}

    <section class="accueil">
        <div class="d-flex justify-content-center align-items-center" style="text-align: center; min-height: 50vh;">
            <div>
                <img src="{% static 'images/TB5.jpg' %}" alt="" width="150px" style="border-radius: 30px;">
                <h1 style="font-size: 2rem; color: #fff;">A propos de Trust Business Five</h1>
            </div>
        </div>
    </section>
    <section class="apropos" style="background-color: #2e7d322a;">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div style="margin: 10px;">
                        <h3 style="text-align: center; color: #2e7d32; font-size: 35px;">Historique</h3>
                        <p>
                            Le <strong>Trust Business Five Sarl</strong> est une société à responsabilité limitée qui 
                            a été créé le 19 octobre 2018 pour pallier aux insuffisances d'offres 
                            des services de qualité en République Démocratique du Congo et à 
                            l'étranger.
                        </p>
                        <p>
                            Le <strong>Trust Business Five Sarl</strong> offre une gamme étendue des services dans 
                            le domaine de la technologie/informatique général, des énergies et des 
                            énergies renouvelables afin de répondre aux besoins spécifiques de notre 
                            clientèle du secteur municipal et des secteurs industriel, commercial et 
                            institutionnel.
                        </p>
                        <p>
                            Filiale connexe : très sollicité par une clientèle multiple elle a depuis 
                            sa création donnée naissances à quelques filiales installées dans la 
                            République démocratique du Congo pour satisfaire à ces clients.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="d-flex justify-content-center">
                        <img src="{% static 'images/DRG.jpg' %}" alt="" width="70%" style="border-radius: 30px; box-shadow: 0 0 6px #2e7d32;">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="vision" style="background-color: #2e7d32;">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="d-flex justify-content-center">
                        <img src="{% static 'images/DGG.jpg' %}" alt="" width="60%" style="border-radius: 30px; box-shadow: 0 0 6px #68a76c;">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div style="margin: 10px; color: #fff;">
                        <h3 style="text-align: center; font-size: 35px;">Vision</h3>
                        <p>
                            Le succès par l'entreprenariat et le partenariat. Devenir un chef de file 
                            dans la prestation de service de qualité dans nos domaines d'expertise 
                            disons construction générale, assainissement, environnement, reboisement, 
                            les nouvelles technologies de communication et dans plusieurs autres 
                            domaines.
                        </p>
                        <p>
                            En traitant avec les entités publiques dans le cadre du partenariat public-privé, 
                            et avec les privés; nous visons d'établir des relations solides avec notre 
                            clientèle d'ici 10 ans, devenir une référence en matière de coordination et/ou 
                            d'appui conseil des (aux) activités de reboisement, de gestion de forêts et de 
                            l'environnement, d'assainissement, de construction générale, des nouvelles 
                            technologies de communication et dans d'autres domaines.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="activities">
        <div class="container">
            <h1>Nos activités</h1>
            <div class="row d-flex">
                <div class="col-lg-4">
                    <div class="boxacti">
                        <p><i class="bi bi-clipboard-data"></i></p>
                        <h4>Bureau d'études</h4>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="boxacti">
                        <p><i class="bi bi-briefcase"></i></p>
                        <h4>Facilitation d'affaires</h4>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="boxacti">
                        <p><i class="bi-building"></i></p>
                        <h4>Construction et réhabilitation (Génie civil)</h4>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="boxacti">
                        <p><i class="bi bi-people"></i></p>
                        <h4>
                            Appui conseil dans la coordination des activités
                        </h4>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="boxacti">
                        <p><i class="bi bi-lightbulb"></i></p>
                        <h4>Innovation en nouvelle technologie-Commerces</h4>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="expert" style="background-color: #2e7d32; color: #fff;">
        <div class="container d-flex justify-content-center">
            <p style="text-align: center;">
                Le <strong>Trust Business Five Sarl</strong> dans l'accomplissement de ses 
                objectifs opérationnels  accompagne plusieurs associations 
                locales dans la  conception des projets, dans la promotion 
                de l'agriculture, le reboisement et l'assainissement des 
                milieux.
            </p>
        </div>
    </section>

{% endblock %}

templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-DCFJTVL769"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-DCFJTVL769');
    </script>

    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo/LOGO PNG TRUST.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/files.css' %}">
    <link rel="stylesheet" href="{% static 'css/dom.css' %}">
    <title>Trust Business Five Sarl</title>
</head>

<body>
    <div id="home" class="navbar">
        <div class="d-flex align-items-center flex-column d-lg-none">
            <img src="{% static 'images/menu.png' %}" onclick="showMenu()" alt="menu-bar" style="width: 30px; cursor: pointer;">
        </div>
        <a class="logo" href="{% url 'home:home' %}"><img class="logo" src="{% static 'images/logo/LOGO PNG TRUST.png' %}" alt=""></a>
        <ul class="nav d-none d-lg-flex">
            <li><a href="{% url 'home:home' %}">Accueil</a></li>
            <li><a href="{% url 'home:home' %}#Missions">Missions</a></li>
            <li class="dropdown">
                <a href="#">Domaines d'expertise</a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'home:env' %}">Environnement</a></li>
                    <li><a href="{% url 'home:reb' %}">Reboisement et gestion des forêts</a></li>
                    <li><a href="{% url 'home:agri' %}">Agriculture</a></li>
                    <li><a href="{% url 'home:infra' %}">Infrastructure</a></li>
                    <li><a href="{% url 'home:econ' %}">Economie</a></li>
                    <li><a href="{% url 'home:urgence' %}">Urgence et gestion des conflits</a></li>
                </ul>
            </li>
            <li><a href="{% url 'home:offres' %}">Offres</a></li>
            <li><a href="{% url 'home:programme' %}">Programmes</a></li>
            <li><a href="{% url 'home:about' %}">À propos</a></li>
            <li><a href="{% url 'home:home' %}#contact">Contact</a></li>
        </ul>
        <div>
            <!-- <form action="{% url 'home:search' %}" method="post"> -->
                <!-- {% csrf_token %} -->
                <input type="search" style="font-size: 0.8rem; padding: 4px 5px;" placeholder="Rechercher"><a class="sear" href="#" ><i class="bi bi-search"></i></a>
                <!-- <input type="submit" style="font-size: 0.8rem; padding: 4px 5px;" placeholder="Rechercher"><a class="sear" href="#" ><i class="bi bi-search"></i></a> -->
            <!-- </form> -->
        </div>

        <!-- Menu responsive -->
        <div id="menu-responsive" class="menu-responsive hide-menu d-lg-none">
            <ul class="nav position-absolute">
                <div style="position: absolute; right: 10px; top: 10px; padding: 5px; z-index: 999;">
                    <img src="{% static 'images/menu.png' %}" alt="menu bar" style="width: 25px; cursor: pointer;"  onclick="showMenu()">
                </div>
                <li><a href="{% url 'home:home' %}">Accueil</a></li>
                <li><a href="#Missions">Missions</a></li>
                <li class="dropdown">
                    <a href="#">Domaines d'expertise</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'home:env' %}">Environnement</a></li>
                        <li><a href="{% url 'home:reb' %}">Reboisement et gestion des forêts</a></li>
                        <li><a href="{% url 'home:agri' %}">Agriculture</a></li>
                        <li><a href="{% url 'home:infra' %}">Infrastructure</a></li>
                        <li><a href="{% url 'home:econ' %}">Economie</a></li>
                        <li><a href="{% url 'home:urgence' %}">Urgence et gestion des conflits</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'home:offres' %}">Offres</a></li>
                <li><a href="{% url 'home:programme' %}">Projets</a></li>
                <li><a href="{% url 'home:about' %}">À propos</a></li>
                <li><a href="{% url 'home:home' %}#contact">Contact</a></li>
            </ul>
            <div style="position: absolute;" onclick="showMenu()"></div>
        </div>
    </div>

    <div class="overlay" id="overlay"></div>
    <div class="custom-alert" id="customAlert">
        <h2>Notification</h2>
        <hr>
        <p id="alertMessage"></p>
        <button onclick="closeAlert()">OK</button>
    </div>

    {% block content %}{% endblock %}

    <div class="voil">
        <h4>Nos partenairs</h4>
        <div>
            <img src="{% static 'images/logo/LOGO (2).png' %}" alt="" style="width: 110px;">
            <img src="{% static 'images/logo/logo_get_skills_class.png' %}" alt="" style="width: 110px;">
        </div>
        <div>
            <img src="{% static 'images/logo/LOGO-ENVIRONNEMENT-DEV-e1651049635425.png' %}" alt="" style="width: 110px;">
            <img src="{% static 'images/logo/LOGO (2).png' %}" alt="" style="width: 110px;">
        </div>
        <div>
            <img src="{% static 'images/logo/brave man ok_104331.png' %}" alt="" style="width: 110px;">
            <img src="{% static 'images/logo/ECO.png' %}" alt="" style="width: 110px;">
        </div>
    </div>

    <section class="prefooter py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 services">
                    <h4 style="color: #fff;">Services et activités</h3>
                    <div>
                        <ul>
                            <li>Bureau d'études</li>
                            <li>Facilitation d'affaires</li>
                            <li>
                                Appui conseil dans la coordination 
                                des activités de gestion de 
                                l'environnement, reboisement, gestion 
                                des forêts et assainissement
                            </li>
                            <li>Construction et réhabilitation (Génie civil)</li>
                            <li>Informatique/innovation en nouvelle technologie Commerces générales</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 partenairs">
                    <div></div>
                </div>
                <div class="col-lg-4 bref">
                    <h4 style="color: #fff;">Trust Business Five</h4>
                    <p>
                        Trust Business Five est une société à responsabilité 
                        limitée qui a été créé pour pallier aux insuffisances 
                        d'offres des services de qualité en République 
                        Démocratique du Congo et à l'étranger.
                    </p>
                    <a href="{% url 'home:devis-form' %}">Demander un devis</a>
                </div>
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <hr>
            <div class="content">
                <img src="{% static 'images/TB5.jpg' %}" alt="">
                <div class="partainers">
                    <p class="m-0"><a href="http://plu.us/TB5" target="_blank" class="text-white"><i class="bi bi-universal-access"></i></a></p> &nbsp;&nbsp;&nbsp;
                    <p class="m-0"><a href="http://plu.us/TB5" target="_blank" class="text-white"><i class="bi bi-x-diamond-fill"></i></a></p>
                </div>
                <div class="social">
                    <a target="_blank" href="https://www.facebook.com/people/Trust-Business-Five/61566912243431/?rdid=rcQJ3lrhWXJltUVv&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2F14rrLd1fRr%2F"><i class="bi bi-facebook" style="color: rgb(0, 89, 255);"></i></a>
                    <a target="_blank" href="https://x.com/trust_business5"><img src="{% static 'images/logo/twitter.png' %}" alt="" style="width: 1.1rem; margin-top: -2px;"></a>
                    <a target="_blank" href="https://www.linkedin.com/company/trust-business-five"><i class="bi bi-linkedin" style="color: rgb(0, 89, 255);"></i></a>
                    <a target="_blank" href="https://www.youtube.com/@TrustBusinessFive"><i class="bi bi-youtube" style="color: red;"></i></a>
                </div>
            </div>
            <hr>
            <p class="TDR">&copy; 2024 TRUST BUSINESS FIVE Sarl. Tous droits réservés.</p>
        </div>
    </footer>

    <button onclick="topFunction()" id="myBtn" class="btn btn-primary">&uparrow;</button>

    <script>
        let menuResp = document.getElementById("menu-responsive");

        function showMenu () {
            menuResp.classList.toggle('hide-menu');
            menuResp.classList.toggle('show-menu');
        }



        let mybutton = document.getElementById("myBtn");

        //Afficher le bouton retour en haut
        window.onscroll = function(){scrollFunction()};

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }

        // Lorsque l'utilisateur clique sur le bouton, retour en haut
        function topFunction() {
            document.body.scrollTop = 0; 
            document.documentElement.scrollTop = 0;
        }

        // Vérification du remplissage des champs et affichage de la boîte de dialogue
        let formToSubmit = null;

        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('myForm').addEventListener('submit', function(event) {
                event.preventDefault(); // Empêche l'envoi du formulaire

                let form = event.target;
                let allFilled = true;
                let fields = form.querySelectorAll('input[type="text"], input[type="email"]');

                fields.forEach(function(field) {
                    if (!field.value) {
                        allFilled = false;
                        field.style.borderColor = 'red'; // Met en évidence les champs non remplis
                    } else {
                        field.style.borderColor = ''; // Réinitialise la bordure si le champ est rempli
                    }
                });

                if (allFilled) {
                    formToSubmit = form;
                    showAlert('L\'équipe de Trust Business Five vous remercie pour votre message, \n nous restons ouvert pour toute vos préoccupation. \n Cliquez sur OK pour quitter');
                } else {
                    showAlert('Veuillez remplir tous les champs.');
                }
            });
        });

        function showAlert(message) {
            document.getElementById('alertMessage').innerText = message;
            document.getElementById('customAlert').style.display = 'block';
            document.getElementById('overlay').style.display = 'block';
        }

        function closeAlert() {
            document.getElementById('customAlert').style.display = 'none';
            document.getElementById('overlay').style.display = 'none';
            if (formToSubmit) {
                formToSubmit.submit(); // Soumet le formulaire après la fermeture de l'alerte
                formToSubmit = null;
            }
        }
    </script>
</body>
</html>

templates/home/offres.html
{% extends './base.html' %}
{% load static %}
{% block content %}

    <section class="accueil">
        <div class="container">
            <h1 class="text-center text-white p-2">Offres</h1>
            {% if offres %}
            {% for offre in offres %}
            <div class="row m-0">
                <div class="col-lg-6">
                    <div class="bg-white m-2" style="border-radius: 10px;">
                        <h4 class="text-center">{{offre.title}}</h4>
                        <hr class="m-2">
                        <p class="m-0">{{offre.detail}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h4 class="text-center text-white">Aucune offre pour le moment</h4>
            {% endif %}
        </div>
    </section>

{% endblock %}

templates/home/search.html
{% extends './base.html' %}
{% load static %}
{% block content %}
    <section style="
    background-color: #2e7d32;
    height: 100vh;
    padding: 40px;
    text-align: center;">
        <div class="container">
            <div class="content d-flex justify-content-center">
                <div>
                    <img src="/static/images/Error500.png" alt="" width="35%">
                    <p style="
                    color: #fff;
                    font-size: 25px;">
                        <span style="font-weight: 900; color: #ffd900;">Les informations que vous recherchez sont introuvables</span> <br>
                    </p>
                    <a href="{% url 'home:home' %}" style="text-decoration: none; color: #2e7d32; background-color: #fff; padding: 10px 20px; font-weight: bold; box-shadow: 0 0 10px #73ff00;">Retour à la page d'accueil</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}