accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('dash/', views.Dash, name='dash'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home, name='home'),
    path('programme', views.Programme, name='programme'),
    path('offres', views.Offres, name='offres'),
    path('about', views.About, name='about'),
    path('jophi_soja', views.Soja, name='soja'),
    path('search/', views.search, name='search'),

    path('domaine/agriculture', views.DomaineAgri, name='agri'),
    path('domaine/economie', views.DomaineEcon, name='econ'),
    path('domaine/environement', views.DomaineEnv, name='env'),
    path('domaine/infrastructure', views.DomaineInfra, name='infra'),
    path('domaine/reboisement', views.DomaineReb, name='reb'),
    path('domaine/urgence', views.DomaineUrgence, name='urgence'),

    path('mission/formulaire-devis', views.DevisForm, name='devis-form'),
    
    path('ecoplus', views.Ecoplus, name='ecoplus'),
    path('dashboard/', views.Dashboard, name='dash'),

    path('addMission/', views.addMission.as_view(), name='addMission'),
    path('showMission/', views.showMission, name='showMission'),
    path('updateMission/<pk>', views.updateMission.as_view(), name='updateMission'),

    path('addDomaine/', views.addDomaine.as_view(), name='addDomaine'),
    path('showDomaine/', views.showDomaine, name='showDomaine'),
    path('updateDomain/<pk>', views.updateDomaine.as_view(), name='updateDomain'),
    path('deleteDomain/<pk>', views.deleteDomaine, name='deleteDomain'),

    path('addContact/', views.addContact.as_view(), name='addContact'),
    path('showContact/', views.showContact, name='showContact'),

    path('addOffre/', views.addOffre.as_view(), name='addOffre'),
    path('showOffre/', views.showOffre, name='showOffre'),

    path('addCommande/', views.addCommandeSoja.as_view(), name='addCommande'),
    path('showCommande/', views.showCommandeSoja, name='showCommande'),
]

tbf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
 
# Custom 404 error view
handler404 = 'home.views.error_404' 
# Custom 500 error view
handler500 = 'home.views.error_500' 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

class Mission(models.Model):
    image = models.ImageField(upload_to="image/")
    title = models.CharField(max_length=100)
    desc = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.title}'

class Domaine(models.Model):
    parent = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="domaine/")
    detail = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.title} - {self.parent}'

class Offre(models.Model):
    title = models.CharField(max_length=50)
    detail = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="domaine/", blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.title}'

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} ({self.email})'

class CommandeSoja(models.Model):
    name = models.CharField(max_length=50)
    midname = models.CharField(max_length=50)
    firstname = models.CharField(max_length=50)
    email = models.EmailField()
    numero = models.CharField(max_length=50)
    adress = models.CharField(max_length=50)
    quantite = models.CharField(max_length=5)
    details = models.TextField(null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} {self.midname} {self.firstname} {self.numero}'

templates/dash/addDomaine.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil addMission">
        <div class="container">
            <div class="row justify-content-center m-0">
                <form method="post" enctype="multipart/form-data" class="bg-white p-3" style="border-radius: 10px; max-width: 40rem;">
                    <h3 class="my-4">Ajouter un domaine</h3>
                    {% csrf_token %}
                    <label for="id_parent" class="d-block mb-3">
                        Domaine
                        <select name="parent" id="id_parent" class="form-control" required>
                            <option value="" selected disabled>Choisissez un domaine</option>
                            <option value="environement">Environement</option>
                            <option value="reboisement">Reboisement et gestion des forêts</option>
                            <option value="agriculture">Agriculture</option>
                            <option value="infrastructure">Infrastructure</option>
                            <option value="economie">Economie</option>
                            <option value="urgence">Urgence et gestion des conflits</option>
                        </select>
                    </label>
                    <label for="id_title" class="d-block mb-3">
                        Titre
                        {{form.title}}
                    </label>
                    <label for="id_image" class="d-block mb-3">
                        Image
                        {{form.image}}
                    </label>
                    <label for="id_detail" class="d-block mb-3">
                        Detail
                        {{form.detail}}
                    </label>
                    <button type="submit" class="btn btn-success">Envoyer</button>
                </form>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/addMission.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil addMission">
        <div class="container">
            <div class="row justify-content-center m-0">
                <form method="post" enctype="multipart/form-data" class="bg-white p-3" style="border-radius: 10px; max-width: 40rem;">
                    <h3 class="my-4">Ajouter une mission</h3>
                    {% csrf_token %}
                    <label for="id_title" class="d-block mb-3">
                        Titre
                        {{form.title}}
                    </label>
                    <label for="id_image" class="d-block mb-3">
                        Image
                        {{form.image}}
                    </label>
                    <label for="id_desc" class="d-block mb-3">
                        Description
                        {{form.desc}}
                    </label>
                    <button type="submit" class="btn btn-success">Envoyer</button>
                </form>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/addOffre.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil addMission">
        <div class="container">
            <div class="row justify-content-center m-0">
                <form method="post" enctype="multipart/form-data" class="bg-white p-3" style="border-radius: 10px; max-width: 40rem;">
                    <h3 class="my-4">Ajouter une offre</h3>
                    {% csrf_token %}
                    <label for="id_title" class="d-block mb-3">
                        Titre
                        {{form.title}}
                    </label>
                    <label for="id_desc" class="d-block mb-3">
                        Details
                        {{form.detail}}
                    </label>
                    <label for="id_image" class="d-block mb-3">
                        Image
                        {{form.image}}
                    </label>
                    <button type="submit" class="btn btn-success">Envoyer</button>
                </form>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/commandes.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil">
        <div class="container">
            <div class="row m-0">
                <div class="col-lg-2 mb-2">
                    {% include './dashMenu.html' %}
                </div>
                <div class="col-lg-10 mb-2">
                    {% if commandes %}
                    <div class="d-flex align-items-center mb-2">
                        <h3 class="text-white">Commandes</h3> &nbsp;&nbsp;
                    </div>
                    <div class="table-responsive">
                        <table class="table bg-white" style="border-radius: 10px;">
                            <thead>
                                <th>
                                    <td>Nom</td>
                                    <td>Post-nom</td>
                                    <td>Prénom</td>
                                    <td>Email</td>
                                    <td>Numéro</td>
                                    <td>Adresse</td>
                                    <td>Quantité</td>
                                    <td>Details</td>
                                </th>
                            </thead>
                            <tbody>
                                {% for item in commandes %}
                                <tr>
                                    <td></td>
                                    <td>{{item.name}}</td>
                                    <td>{{item.midname}}</td>
                                    <td>{{item.firstname}}</td>
                                    <td>{{item.email}}</td>
                                    <td>{{item.numero}}</td>
                                    <td style="min-width: 10rem;">{{item.adress}}</td>
                                    <td>{{item.quantite}}</td>
                                    <td>{{item.details}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% else %}
                    <h3 class="text-center text-white mb-3"><i>Aucune commande effectuée pour l'instant</i></h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/contacts.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil">
        <div class="container">
            <div class="row m-0">
                <div class="col-lg-2 mb-2">
                    {% include './dashMenu.html' %}
                </div>
                <div class="col-lg-10 mb-2">
                    {% if contacts %}
                    <div class="d-flex align-items-center mb-2">
                        <h3 class="text-white">Contacts</h3> &nbsp;&nbsp;
                    </div>
                    <div class="table-responsive">
                        <table class="table bg-white" style="border-radius: 10px;">
                            <thead>
                                <th>
                                    <td>Nom</td>
                                    <td>Email</td>
                                    <td>Message</td>
                                </th>
                            </thead>
                            <tbody>
                                {% for item in contacts %}
                                <tr>
                                    <td></td>
                                    <td>{{item.name}}</td>
                                    <td>{{item.email}}</td>
                                    <td style="min-width: 30rem;">{{item.message}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% else %}
                    <h3 class="text-center text-white mb-3"><i>Aucune donnée enregistrée pour l'instant</i></h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/dash.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil">
        <div class="container text-center">
            <h1 class="text-center text-white p-2">Dashboard</h1>
            <a href="{% url 'home:showMission' %}" class="btn btn-success mb-2">Gérer les missions</a><br>
            <a href="{% url 'home:showDomaine' %}" class="btn btn-success mb-2">Gérer les domaines d'expertise</a><br>
            <a href="{% url 'home:showOffre' %}" class="btn btn-success mb-2">Gérer les offres</a><br>
            <a href="{% url 'home:showContact' %}" class="btn btn-success mb-2">Gérer les contacts</a><br>
            <a href="{% url 'home:showCommande' %}" class="btn btn-success mb-2">Gérer les commandes</a><br>
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger mb-2">Déconnexion</a><br>
        </div>
    </section>

{% endblock %}

templates/dash/dashMenu.html
            <a href="{% url 'home:showMission' %}" class="btn btn-success mb-2">Gérer les missions</a><br>
            <a href="{% url 'home:showDomaine' %}" class="btn btn-success mb-2">Gérer les domaines d'expertise</a><br>
            <a href="{% url 'home:showOffre' %}" class="btn btn-success mb-2">Gérer les offres</a><br>
            <a href="{% url 'home:showContact' %}" class="btn btn-success mb-2">Gérer les contacts</a><br>
            <a href="{% url 'home:showCommande' %}" class="btn btn-success mb-2">Gérer les commandes</a><br>
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger mb-2">Déconnexion</a><br>
            

templates/dash/domaines.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil">
        <div class="container">
            <div class="row m-0">
                <div class="col-lg-2 mb-2">
                    {% include './dashMenu.html' %}
                </div>
                <div class="col-lg-10 mb-2">
                    {% if domaines %}
                    <div class="d-flex align-items-center mb-2">
                        <h3 class="text-white">Nos domaines</h3> &nbsp;&nbsp;
                        <a href="{% url 'home:addDomaine' %}">Ajouter une domaine</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table bg-white" style="border-radius: 10px;">
                            <thead>
                                <th>
                                    <td>Image</td>
                                    <td>Titre</td>
                                    <td>Domaine</td>
                                    <td>Details</td>
                                    <td>Actions</td>
                                </th>
                            </thead>
                            <tbody>
                                {% for item in domaines %}
                                <tr>
                                    <td></td>
                                    <td><img src="{{item.image.url}}" width="70" height="50" alt="{{item.title}}"></td>
                                    <td>{{item.title}}</td>
                                    <td>{{item.parent}}</td>
                                    <td style="min-width: 30rem;">{{item.detail}}</td>
                                    <td>
                                        <a href="{% url 'home:updateDomain' item.pk %}" class="btn btn-warning mb-1">Modifier</a>
                                        <form action="{% url 'home:deleteDomain' item.pk %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger mb-1">Supprimer</button>
                                        </form>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% else %}
                    <div class="text-center">
                        <h3 class="text-white mb-3"><i>Aucune donnée enregistrée pour l'instant</i></h3>
                        <a href="{% url 'home:addDomaine' %}" class="btn btn-success w-50">Ajouter une domaine</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/login.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil">
        <div class="container">
            <h1 class="text-center text-white p-2">Se connecter</h1>
            <div class="d-flex justify-content-center">
                <form method="post" style="padding: 20px; border-radius: 10px; background-color: #fff; width: 20rem;">
                    {% csrf_token %}
                    <label for="username" class="d-block mb-2">
                        Nom d'utilisateur
                        <input type="text" class="form-control w-100" name="username" id="username" required>
                    </label>
                    <label for="password" class="d-block mb-2">
                        Mot de passe
                        <input type="password" class="form-control w-100" name="password" id="password" required>
                    </label>
                    <button type="submit" class="btn btn-success">Connexion</button>
                </form>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/missionForm.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil addMission">
        <div class="container">
            <div class="row justify-content-center m-0">
                <form method="post" enctype="multipart/form-data" class="bg-white p-3" style="border-radius: 10px; max-width: 40rem;">
                    <h3 class="my-4">Ajouter une mission</h3>
                    {% csrf_token %}
                    <label for="id_title" class="d-block mb-3">
                        Titre
                        {{form.title}}
                    </label>
                    <label for="id_image" class="d-block mb-3">
                        Image
                        {{form.image}}
                    </label>
                    <label for="id_desc" class="d-block mb-3">
                        Description
                        {{form.desc}}
                    </label>
                    <button type="submit" class="btn btn-success">Envoyer</button>
                </form>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/missions.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil">
        <div class="container">
            <div class="row m-0">
                <div class="col-lg-2 mb-2">
                    {% include './dashMenu.html' %}
                </div>
                <div class="col-lg-10 mb-2">
                    {% if missions %}
                    <div class="d-flex align-items-center mb-2">
                        <h3 class="text-white">Nos missions</h3> &nbsp;&nbsp;
                        <a href="{% url 'home:addMission' %}">Ajouter une mission</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table bg-white" style="border-radius: 10px;">
                            <thead>
                                <th>
                                    <td>Image</td>
                                    <td>Titre</td>
                                    <td>Description</td>
                                    <td>Actions</td>
                                </th>
                            </thead>
                            <tbody>
                                {% for item in missions %}
                                <tr>
                                    <td></td>
                                    <td><img src="{{item.image.url}}" width="70" height="50" alt="{{item.title}}"></td>
                                    <td>{{item.title}}</td>
                                    <td style="min-width: 30rem;">{{item.desc}}</td>
                                    <td>
                                        <a href="{% url 'home:updateMission' item.id %}" class="btn btn-warning mb-1">Modifier</a>
                                        <a href="#" class="btn btn-danger mb-1">Supprimer</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% else %}
                    <div class="text-center">
                        <h3 class="mb-3"><i class="text-white">Aucune donnée enregistrée pour l'instant</i></h3>
                        <a href="{% url 'home:addMission' %}" class="btn btn-success w-50">Ajouter une mission</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/offres.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil">
        <div class="container">
            <div class="row m-0">
                <div class="col-lg-2 mb-2">
                    {% include './dashMenu.html' %}
                </div>
                <div class="col-lg-10 mb-2">
                    {% if offres %}
                    <div class="d-flex align-items-center mb-2">
                        <h3 class="text-white">Nos offres</h3> &nbsp;&nbsp;
                        <a href="{% url 'home:addOffre' %}">Ajouter une offre</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table bg-white" style="border-radius: 10px;">
                            <thead>
                                <th>
                                    <td>Titre</td>
                                    <td>Details</td>
                                    <td>Actions</td>
                                </th>
                            </thead>
                            <tbody>
                                {% for item in details %}
                                <tr>
                                    <td></td>
                                    <td>{{item.title}}</td>
                                    <td style="min-width: 30rem;">{{item.detail}}</td>
                                    <td>
                                        <a href="{% url 'home:updateMission' item.id %}" class="btn btn-warning mb-1">Modifier</a>
                                        <a href="#" class="btn btn-danger mb-1">Supprimer</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% else %}
                    <div class="text-center">
                        <h3 class="mb-3"><i class="text-white">Aucune donnée enregistrée pour l'instant</i></h3>
                        <a href="{% url 'home:addOffre' %}" class="btn btn-success w-50">Ajouter une offre</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/updateDomaine.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil addMission">
        <div class="container">
            <div class="row justify-content-center m-0">
                <form method="post" enctype="multipart/form-data" class="bg-white p-3" style="border-radius: 10px; max-width: 40rem;">
                    <h3 class="my-4">Modifier le domaine</h3>
                    {% csrf_token %}
                    <label for="id_parent" class="d-block mb-3">
                        Domaine
                        <select name="parent" id="id_parent" class="form-control" required>
                            <option value="" selected disabled>-- Choisissez un domaine --</option>
                            <option value="environement">Environement</option>
                            <option value="reboisement">Reboisement et gestion des forêts</option>
                            <option value="agriculture">Agriculture</option>
                            <option value="infrastructure">Infrastructure</option>
                            <option value="economie">Economie</option>
                            <option value="urgence">Urgence et gestion des conflits</option>
                        </select>
                    </label>
                    <label for="id_title" class="d-block mb-3">
                        Titre
                        {{form.title}}
                    </label>
                    <label for="id_detail" class="d-block mb-3">
                        Details
                        {{form.detail}}
                    </label>
                    <label for="id_image" class="d-block mb-3">
                        Image
                        {{form.image}}
                    </label>
                    <button type="submit" class="btn btn-success">Modifier</button>
                </form>
            </div>
        </div>
    </section>

{% endblock %}

templates/dash/updateMission.html
{% extends '../home/base.html' %}
{% block content %}

    <section class="accueil addMission">
        <div class="container">
            <div class="row justify-content-center m-0">
                <form method="post" enctype="multipart/form-data" class="bg-white p-3" style="border-radius: 10px; max-width: 40rem;">
                    <h3 class="my-4">Modifier la mission</h3>
                    {% csrf_token %}
                    <label for="id_title" class="d-block mb-3">
                        Titre
                        {{form.title}}
                    </label>
                    <label for="id_image" class="d-block mb-3">
                        Image
                        {{form.image}}
                    </label>
                    <label for="id_desc" class="d-block mb-3">
                        Description
                        {{form.desc}}
                    </label>
                    <button type="submit" class="btn btn-success">Modifier</button>
                </form>
            </div>
        </div>
    </section>

{% endblock %}